devtools::load_all()
pc_titles <- get_pc_titles()
titles_eng <- readLines(file.path(pc_titles$all_lang, "eng.txt"))
titles_eng <- tm::VCorpus(tm::VectorSource(eng))
usethis::use_data(titles_eng, overwrite=T)
titles_cat <- plain_to_corpus(pc_titles$cat_lang)
usethis::use_data(titles_cat, overwrite=T)
titles_mpi <- plain_to_corpus(pc_titles$mpi_lang)
usethis::use_data(titles_mpi, overwrite=T)
titles_pers <- plain_to_corpus(pc_titles$pers_lang)
usethis::use_data(titles_pers, overwrite=T)
